language: ruby
rvm:
  - "1.8.7"
jdk:
  - oraclejdk7
before_install:
  - gem update --system
  - gem --version
install:
  bundle install
script:
  bundle exec buildr clean test:'-SpaceAfterCommaRuleTest'
  